class ErrorCode {
  ErrorCode._();
  static const EMAIL = 'USER.EMAIL_EXISTED';
  static const USER_OR_EMAIL_NOT_CORRECT = "AUTH.USER_OR_EMAIL_NOT_CORRECT";
  static const REGISTERED_MUST_VERIFY_EMAIL =
      "USER.REGISTERED_MUST_VERIFY_EMAIL";
  static const POSITION_ITEM_IN_USED = "POSITION.ITEM_IN_USED";
  static const OTP_FAIL = "AUTH.OTP_FAIL";
  static const USERNAME_EXISTED = "USER.USERNAME_EXISTED";
  static const USER_EMAIL_EXISTED = "ABILITY.USER_EMAIL_EXISTED";
  static const PARENT_ID_NOT_EXIST = "DEPT.PARENT_ID_NOT_EXIST";
  static const USER_VERIFIED = "AUTH.USER_VERIFIED";
  static const GOAL_ITEM_IN_USER = 'GOAL.ITEM_IN_USED';
  static const INPUT_VALID = '010009';
  static const CANNOT_EXECUTE_ACTION = 'POLICY.CANNOT_EXECUTE_ACTION';
  static const SERVER_FAULT_CODE = 'SERVER_FAULT_CODE';
  static const REQUIRE_HEADER = 'WORK_PLACE.REQUIRE_HEADER_VALUE';
  static const DISPLAY_NAME_SLUG_EXISTED =
      'NEWS_CATEGORY.DISPLAY_NAME_SLUG_EXISTED';
  static const DEPT_HAS_CHILDREN = 'DEPT.HAS_CHILDREN';
  static const DEPT_ITEM_IN_USED = 'DEPT.ITEM_IN_USED';
  static const FOLDER_ITEM_IN_USED = 'FOLDER.ITEM_IN_USED';
}